[project]
name = 'Tokenized-Accounts-Receivable'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.credit-assessment]
path = 'contracts/credit-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.invoice-verification]
path = 'contracts/invoice-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
